name             'nuntium'
maintainer       'Juan Wajnerman'
maintainer_email 'jwajnerman@manas.com.ar'
license          'All rights reserved'
description      'Installs/Configures nuntium'
long_description 'Installs/Configures nuntium'
version          '0.1.0'

depends 'build-essential'
depends 'rbenv'
depends 'mysql', '< 6.0.0'
depends 'database', '>= 2.3.1'
depends 'nodejs'
depends 'instedd-common'
depends 'rabbitmq'
depends 'newrelic'
